### ISSUE TITLE
Could not start GtkIDE on Windows 10

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jonathanBieler/GtkIDE.jl#1]
This was on a 64bit machine, with Julia 0.4.2.
When doing:         using GtkIDE

I got the following error:
INFO: Precompiling module Gtk...
ERROR: LoadError: LoadError: UndefVarError: libgtksourceview not defined
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in require at loading.jl:243
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in require at loading.jl:243
while loading C:\Users\CVO.julia\v0.4\GtkSourceWidget\src\GtkSourceWidget.jl, i
n expression starting on line 56
while loading C:\Users\CVO.julia\v0.4\GtkIDE\src\GtkIDE.jl, in expression start
ing on line 29

Thanks

**Comment by jonathanBieler** [comment]
The windows code was a in `@osx_only` for some reason... should be [fixed](https://github.com/jonathanBieler/GtkSourceWidget.jl/commit/a7485bc81c67f2dedb0c0d31735008c898f3c99e) now.

You can try to update the package with `Pkg.checkout("GtkSourceWidget")`, make a new workspace and reuse GktIDE. Hopefully the binaries work also in windows 10, I tested only on windows 7.

**Comment by Ivo-Balbaert** [comment]
Thanks, that worked!
The version on Windows is remarkably stable, I could not let it crash
This is in sharp contrast to the version on my Ubuntu machine, which often crashes by itself after some seconds.
