### ISSUE TITLE
Problems on Ubuntu 15, 64 bit - Julia 0.5dev

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jonathanBieler/GtkIDE.jl#2]
1) Julia commands in console worked
     run_tests() executed

2) Menu item:
File / New crashed IDE + Terminal
File / Open: did not work
File / Quit: did not work

2)
open filename in console: did not work

> julia open "fizzbuzz.jl"
> syntax: extra token """ after end of expression
> 
> julia open fizzbuzz.jl
> syntax: extra token "fizzbuzz" after end of expression

3) Frequently GtkIDE crashed after several seconds/minutes with the following error message in the terminal:
julia> fatal: error thrown and no exception handler available.
ErrorException("schedule: Task not runnable")
rec_backtrace at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
jl_throw at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
enq_work at ./task.jl:310
schedule at task.jl:325
jlcall___schedule#37___25341 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_schedule_25340 at  (unknown line)
jlcall_schedule_25340 at  (unknown line)
notify at task.jl:288
jlcall_notify_25339 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_schedule_24454 at  (unknown line)
jlcall_schedule_24454 at  (unknown line)
notify at task.jl:288
jlcall_notify_24453 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_notify_22723 at  (unknown line)
jlcall_notify_22723 at  (unknown line)
task_done_hook at task.jl:138
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 0x7efbf6deaa7c)
unknown function (ip: (nil))

Thanks for the hard work!

**Comment by jonathanBieler** [comment]
The menus are pretty much placeholders, I haven't worked on them yet.

There's was an error in the readme, it's `edit filename` and not `open`, my bad.

For the crash do you notice any pattern, like it happens when you execute some code, or click somewhere ? There's several @schedule, specially in the console code, so it's hard to say where the issue is. You could also try to disable [output redirection](https://github.com/jonathanBieler/GtkIDE.jl/blob/master/src/GtkIDE.jl#L39), maybe it would give us more info.

Thanks for the feedback.

**Comment by Ivo-Balbaert** [comment]
Ok, edit works now , but when I then try F5, or even when I click in the editor pane or even without doing anything, it crashes without error.
GtkIDE  often but not always crashes by itself after some seconds or minutes, the Julia terminal crashes with it. So I don't get any error message at all.
When I reset error redirection to: const REDIRECT_STDOUT = false, same situation
I can't find anything in the logs as possible error.

Thanks.

**Comment by jonathanBieler** [comment]
I think I fixed the issue, it's was a common problem with Gtk's simple callbacks syntax that crashed only with Julia 0.5.

That said there's other issues with Julia 0.5, but at least it doesn't crash horribly anymore.

**Comment by Ivo-Balbaert** [comment]
Ok, sorry for the delay.
I encountered no more crashes.
I can open and run Julia files.
Thanks!
